### ISSUE TITLE
Adaptar ao RFC

### ISSUE THREAD

**Issue by dleitee** [dleitee/valid.js#18]
Mais uma implementação que não segue a RFC. Olhe [essa implementação](https://github.com/chriso/validator.js): ele valida todos os e-mails de acordo com a RFC, porém de maneira mais controlada, por exemplo dando a opção da parte local não requerer um TLD, o que é útil em vários casos.

Também ele permite e-mails como "mario+social@exemplo.com" por que e-mails assim são válidos pela RFC. Quem criou essa de que "+" significa uma label foi o Gmail. Se quiser filtrar usuários com isso só normalizar o e-mail, algo que a biblioteca permite.

O mais importante: essa implementação aceita, por padrão, e-mails internacionalizados. Caso talvez você não tenha um e-mail "josé-da-silva@exemplo.com", mas isso não significa que no futuro e-mails assim sejam comuns. Em nossa língua isso até não é grande problema, mas e quanto a outras línguas onde tirar um acento muda todo o sentido da palavra? Por acaso o foco dessa biblioteca é só Brasil? (já que é CEP ao invés de "postalCode")

Agora, antes que pense que estou dizendo "largue essa aqui e use a outra", se conseguir fazer o mesmo, mostrando na documentação as diferentes (como "essa biblioteca trata apenas os casos mais comuns") e continuando simples, tudo bem.

**Comment by dleitee** [comment]
@qgustavor aqui tem a implementação da RFC, seria essa? [Regex](http://www.regular-expressions.info/email.html)

**Comment by qgustavor** [comment]
Quando comentei a questão nem era adaptar ao RFC, já que ele tem alguns detalhes que não são aplicáveis em casos gerais:

Por exemplo: e-mails sem TLD (como `admin@mailserver1`) são úteis quando o servidor de e-mail está na rede local. Um caso para isso poderia ser uma ferramenta administrativa, na escolha de um e-mail para envio de relatórios. Porém na maioria dos casos isso não acontece e seria bom filtrar endereços como esse.

Logo seria bom mostrar na documentação se esses e-mails estão sendo filtrados (o que manteria a ferramenta mais simples) ou criar uma opção para escolher isso (como na outra biblioteca).
