### ISSUE TITLE
Add section "how to contribute"on README

### ISSUE THREAD

**Issue by rdiego26** [dleitee/valid.js#32]
A section that I find important is how to contribute, how about this example?

A simple example [this](https://github.com/rdiego26/klefki) .

**Comment by cbsorrilha** [comment]
I can do it.
Should we use the same steps on the repo on the link you've send?

**Comment by rdiego26** [comment]
I think that would be a good start, I'm waiting for some response from @dleitee  to see if it makes sense.

**Comment by minerado** [comment]
I solved this issue on PR #58 thks flws
