### ISSUE TITLE
NPM install fails when use ES6 import

### ISSUE THREAD

**Issue by lucasferreira** [dleitee/valid.js#42]
Hi @dleitee 

I'm trying to use the ES6 import without sucess:

```javascript
import {validate, string, util, isValid} from 'valid.js'
```

The problem (I guess) is the version that are publish at npm registry doesn't contain *dist* folder inside of them. In fact, *dist/validate.js* file is important because they are set as *main* script inside package.json file.

```json
.....
"repository": {
    "type": "git",
    "url": "git+https://github.com/dleitee/valid.js.git"
  },
  "main": "dist/validate.js", // <--- this line...
......
```

Can you please help? I think that you need is just update npm registry with a new version of package.

Thanks!

**Comment by dleitee** [comment]
Hi @lucasferreira 

I removed the dist folder to .gitignore file and published a new version of package.

Can you run npm update and test?

Thanks!

**Comment by lucasferreira** [comment]
Works like a charm @dleitee!

thanks again ;)
