### ISSUE TITLE
Proper email validation

### ISSUE THREAD

**Issue by mateeyow** [dleitee/valid.js#55]
It seems this email: `test@a` will be a valid email address.

```js
console.log(isValid('test@a', util.isEmail))
// => true
```

**Comment by dleitee** [comment]
This is a valid email address. What you think is wrong?

See this article: [https://en.wikipedia.org/wiki/Email_address](https://en.wikipedia.org/wiki/Email_address)

and this [The 100% correct way to validate email addresses](https://hackernoon.com/the-100-correct-way-to-validate-email-addresses-7c4818f24643#.bztnd25sv)

Thanks

**Comment by mateeyow** [comment]
Hmmm. You are right. Thanks!
