### ISSUE TITLE
Logo suggestion

### ISSUE THREAD

**Issue by danilowoz** [dleitee/valid.js#56]
Hi @dleitee 
I saw in #28 you need a logo for the project, so I have a suggestion for you

What do you think?
<img width="983" alt="screen shot 2017-07-30 at 21 28 38" src="https://user-images.githubusercontent.com/4838076/28758450-4e55826c-756e-11e7-9069-4bf5227e57b1.png">

**Comment by dleitee** [comment]
Hey @danilowoz 

It was awesome. Please, could you open a PR adding this logo to the readme.md?

Thanks

**Comment by dleitee** [comment]
merged om #57
